# Site settings
title: Portfolio
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "gbojan.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bojan Gigovski
user_description: Experienced Junior Software Engineer with a demonstrated history of working in the marketing and advertising industry. Skilled in ASP.Net, Cascading Style Sheets (CSS3), Java, SQL, and Unity2D. Strong engineering professional graduated from Faculty of Computer Science and Engineering - Skopje and ready for new challenges.
user_title: Software Developer
email: gigovski_bojan@outlook.com
twitter_username: gigovski_Bojan
github_username:  GBojan
gplus_username:  103365829313614157760

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
